#!/bin/sh

set -e

if [ -n "$DEBUG_STARTUP" ]; then
	set -x
fi

if [ -z "$SEQUEL_DATABASE_URL" ]; then
	echo "No SEQUEL_DATABASE_URL set!" >&2
	exit 1
fi

if [ -z "$MIGRATIONS_DIR" ]; then
	echo "No MIGRATIONS_DIR set!" >&2
	exit 1
fi

if ! [ -d "$MIGRATIONS_DIR" ]; then
	echo "$MIGRATIONS_DIR is not a directory!" >&2
	exit 1
fi

if [ -n "$DEBUG_STARTUP" ]; then
	ls -laR "$MIGRATIONS_DIR"
fi

/usr/local/bundle/bin/sequel -E -m "$MIGRATIONS_DIR" "$SEQUEL_DATABASE_URL"

if [ -n "$PAUSE_ON_COMPLETION" ]; then
	echo "Migration complete.  Time for a nap."
	/pause
fi
